import Layout from '../components/Layout';

function EarningsDisclaimers() {
  return (
    <Layout>
      <div className='container'>
        <div className="row">
          <div className='col'>
            <div style={{ padding: '2rem' }}  className="text-center">
                <h2>EARNINGS & INCOME DISCLAIMER</h2>
            </div>
          </div>
        </div>
        <div className="row">
          <div className='col'>
            <p>ANY EARNINGS OR INCOME STATEMENTS, OR EARNINGS OR INCOME EXAMPLES, ARE ONLY ESTIMATES OF WHAT WE THINK YOU COULD EARN. THERE IS NO ASSURANCE YOU'LL DO AS WELL. IF YOU RELY UPON OUR FIGURES, YOU MUST ACCEPT THE RISK OF NOT DOING AS WELL.</p>
            <p>WHERE SPECIFIC INCOME FIGURES ARE USED, AND ATTRIBUTED TO AN INDIVIDUAL OR BUSINESS, THOSE PERSONS OR BUSINESSES HAVE EARNED THAT AMOUNT. THERE IS NO ASSURANCE YOU'LL DO AS WELL. IF YOU RELY UPON OUR FIGURES, AGAIN, YOU MUST ACCEPT THE RISK OF NOT DOING AS WELL.</p>
            <p>ANY AND ALL CLAIMS OR REPRESENTATIONS, AS TO INCOME EARNINGS ON THIS WEB SITE, ARE NOT TO BE CONSIDERED AS AVERAGE EARNINGS.</p>
            <p>THERE CAN BE NO ASSURANCE THAT ANY PRIOR SUCCESSES, OR PAST RESULTS, AS TO INCOME EARNINGS, CAN BE USED AS AN INDICATION OF YOUR FUTURE SUCCESS OR RESULTS.&nbsp;</p>
            <p>MONETARY AND INCOME RESULTS ARE BASED ON MANY FACTORS. WE HAVE NO WAY OF KNOWING HOW WELL YOU WILL DO, AS WE DO NOT KNOW YOU, YOUR BACKGROUND, YOUR WORK ETHIC, OR YOUR BUSINESS SKILLS OR PRACTICES. THEREFORE, WE DO NOT GUARANTEE OR IMPLY THAT YOU WILL GET &ldquo;RICH&rdquo;, THAT YOU WILL DO AS WELL, OR MAKE ANY MONEY AT ALL. THERE IS NO ASSURANCE YOU'LL DO AS WELL. IF YOU RELY UPON OUR FIGURES, YOU MUST ALWAYS ACCEPT THE RISK OF NOT DOING AS WELL.</p>
            <p>INTERNET BUSINESSES AND EARNINGS DERIVED HAVE UNKNOWN RISKS INVOLVED, AND ARE NOT SUITABLE FOR EVERYONE. MAKING DECISIONS BASED ON ANY INFORMATION PRESENTED IN OUR PRODUCTS, SERVICES, OR WEBSITE, SHOULD BE DONE ONLY WITH THE KNOWLEDGE THAT YOU COULD EXPERIENCE A LOSS, OR MAKE NO MONEY AT ALL.</p>
            <p>ALL PRODUCTS AND SERVICES BY THIS WEBSITE ARE FOR EDUCATIONAL AND INFORMATIONAL PURPOSES ONLY. USE CAUTION AND SEEK THE ADVICE OF QUALIFIED PROFESSIONALS. CHECK WITH YOUR ACCOUNTANT, LAWYER, OR PROFESSIONAL ADVISOR BEFORE ACTING ON THIS OR ANY INFORMATION.&nbsp;</p>
            <p>EARNINGS.<br/>USERS OF OUR PRODUCTS, SERVICES, AND WEBSITE ARE ADVISED TO DO THEIR OWN DUE DILIGENCE WHEN IT COMES TO MAKING BUSINESS DECISIONS, AND ALL INFORMATION, PRODUCTS, AND SERVICES THAT HAVE BEEN PROVIDED SHOULD BE INDEPENDENTLY VERIFIED BY YOUR OWN QUALIFIED PROFESSIONALS. OUR INFORMATION, PRODUCTS, AND SERVICES ON THIS WEBSITE SHOULD BE CAREFULLY CONSIDERED AND EVALUATED BEFORE REACHING A BUSINESS DECISION ON WHETHER TO RELY ON THEM.</p>
            <p>YOU AGREE THAT OUR COMPANY IS NOT RESPONSIBLE FOR THE SUCCESS OR FAILURE OF YOUR BUSINESS DECISIONS RELATING TO ANY INFORMATION PRESENTED BY THIS WEBSITE, OR OUR COMPANY'S PRODUCTS OR SERVICES.</p>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default EarningsDisclaimers;